controller_frequency: 10.0

# Global Costmap Parameters
global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 0.5
  transform_tolerance: 0.5
  static_map: true
  rolling_window: false
  width: 20.0
  height: 20.0
  resolution: 0.05
  inflation_radius: 0.5
  obstacle_range: 2.5
  raytrace_range: 3.0

# Local Costmap Parameters
local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 0.5
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  inflation_radius: 0.3
  obstacle_range: 2.0
  raytrace_range: 3.0

  plugins: 
      - {name: static_layer,            type: "costmap_2d::StaticLayer"}
      - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
      - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}

  static_layer:
      enabled:              true
      map_topic:            "/map"

  inflation_layer:
      enabled:              true
      cost_scaling_factor:  5  
      inflation_radius:     0.3

  obstacle_layer:
      observation_sources: laser_scan_sensor
      footprint_clearing_enabled: true
      laser_scan_sensor: {data_type: LaserScan, sensor_frame: base_link, clearing: true, marking: true, topic: /kinect_scan}

# DWA Local Planner Parameters
DWAPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4
  acc_lim_x: 0.5
  acc_lim_theta: 2.0
  sim_time: 1.0
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 10
  vtheta_samples: 20
  oscillation_reset_dist: 0.05
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1
  holonomic_robot: true
  meter_scoring: true

# Global Planner Parameters
GlobalPlanner:
  allow_unknown: false
  use_dijkstra: false
  use_grid_path: true
  use_astar: true
  planner_window_x: 0.0
  planner_window_y: 0.0
  default_tolerance: 0.5
  publish_potential: false
  orientation_mode: 0
